# Generated by Django 6.1 on 2026-09-17 21:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_eleve_statut_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sanction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Date')),
                ('motif', models.CharField(help_text='Motif de la sanction (ex : perturbation en classe).', max_length=255, verbose_name='Motif')),
                ('sanction', models.CharField(help_text='Sanction appliquée (ex : avertissement, blâme, exclusion…).', max_length=255, verbose_name='Sanction')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanctions', to='academics.eleve')),
            ],
            options={
                'verbose_name': 'Sanction',
                'verbose_name_plural': 'Sanctions',
                'ordering': ['-date'],
            },
        ),
    ]
