# Generated by Django 6.1 on 2026-08-20 23:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('valide', models.BooleanField(default=False)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('numero', models.PositiveSmallIntegerField(choices=[(1, 'Devoir 1'), (2, 'Devoir 2')])),
                ('classe_matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='academics.classematiere')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='academics.eleve')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='academics.semestre')),
            ],
            options={
                'ordering': ['eleve', 'classe_matiere', 'semestre', 'numero'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('eleve', 'classe_matiere', 'semestre', 'numero'), name='uniq_devoir_par_numero'), models.CheckConstraint(condition=models.Q(('numero__in', [1, 2])), name='devoir_numero_valide')],
            },
        ),
        migrations.CreateModel(
            name='Interrogation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('valide', models.BooleanField(default=False)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('classe_matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='academics.classematiere')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='academics.eleve')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='academics.semestre')),
            ],
            options={
                'ordering': ['eleve', 'classe_matiere', 'semestre', 'date_saisie'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('eleve', 'classe_matiere', 'semestre', 'date_saisie'), name='uniq_interro_par_instant')],
            },
        ),
    ]
