# Generated by Django 6.1 on 2026-08-22 00:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conduite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('valide', models.BooleanField(default=False)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conduites', to='academics.eleve')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conduites', to='academics.semestre')),
            ],
            options={
                'ordering': ['eleve', 'semestre'],
                'constraints': [models.UniqueConstraint(fields=('eleve', 'semestre'), name='uniq_conduite_par_semestre')],
            },
        ),
    ]
