# Generated by Django 6.1 on 2026-08-20 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('ABSENCE', 'Absence'), ('RETARD', 'Retard')], default='ABSENCE', max_length=10)),
                ('motif', models.CharField(blank=True, max_length=255)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='academics.eleve')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
